### ISSUE TITLE
Lien image JSON

### ISSUE THREAD

**Issue by KamilGPSEA** [Mairie-de-Saint-Maur/ListApp#2]
Bonjour, 
J'aimerais savoir si il était possible de créer un lien sur les logo dans le fichier JSON

**Comment by camuzic** [comment]
Je ne comprends pas votre demande. Un lien est déjà présent, créé par main.js avec l'URL renseignée dans applis.conf, sur la tuile d'application.
![capture - 2018-12-17 15_33_36](https://user-images.githubusercontent.com/26818513/50093494-25991600-0211-11e9-9cf8-7ca304b060ed.png)

**Comment by KamilGPSEA** [comment]
Certes, mais j'aimerais savoir s'il est possible de créer un lien sûr, par exemple un logo qui link à une doc
